### ISSUE TITLE
When attempting to watch with a channel account, the movement of the summary column is not handled properly.

### ISSUE THREAD

**Issue by ni1chigo2115** [cyfung1031/Tabview-Youtube#19]
![yabyoutubevivaldi](https://github.com/cyfung1031/Tabview-Youtube/assets/23652237/a1f6b903-73f8-4040-ba78-2c2464aa62d7)
For some reason, only on Vivaldi, the summary field does not seem to be functioning properly.

**Comment by cyfung1031** [comment]
Have you installed my other UserScripts like YouTube JS Engine Tamer?
This should be the bug from there, and I have fixed recently. Please update those scripts first.
Please let me know if it works or not.

**Comment by ni1chigo2115** [comment]
> Have you installed my other UserScripts like YouTube JS Engine Tamer? This should be the bug from there, and I have fixed recently. Please update those scripts first. Please let me know if it works or not.

It was no good.
I disabled every script and extension, even Vivaldi's content blocker, but the problem persisted.

**Comment by ni1chigo2115** [comment]
OK, I found the problem, the overview field does not seem to function properly when trying to watch with a derived channel account (not a personal account). (I have established a channel account to watch with my HN)

**Comment by cyfung1031** [comment]
Right now I cannot reproduce this from my side. It might be due to new feature rolling out to different accounts.

1) Try install [v4.34.2](https://greasyfork.org/en/scripts/428651-tabview-youtube?version=1255487). See if it works or not.
2) Try install [youtube-experiment-flags-tamer](https://greasyfork.org/en/scripts/470428-youtube-experiment-flags-tamer) or [youtube-experiment-flags-tamer-basic](https://greasyfork.org/en/scripts/473685-youtube-experiment-flags-tamer-basic)

If both installed and still not working, please let me know although I think in the short term I cannot provide a bug fix for this.

**Comment by ni1chigo2115** [comment]
Neither did it work. The summary field in the tabbed view does not work for "Brand Account."
It should have worked in the past....strange, I wonder if there has been a change in Google's specs.

**Comment by ni1chigo2115** [comment]
You know the difference between a brand account (channel account) and a regular account, right?
A branded account can be freely named and can have any user ID, whereas a regular account must have a first and last name.

**Comment by cyfung1031** [comment]
I don't have brand account.
I don't think there could be any difference in terms of the youtube watch page layout with brand account.

Anyway, I cannot fix it right now.

**Comment by cyfung1031** [comment]
### Try Old Version
You might install the old version (by checking the date that worked for you before) to see if it helps or not.
https://greasyfork.org/en/scripts/428651-tabview-youtube/versions

### Possible Root Cause: The old page info data is removed from your page layout

The info content is from the old youtube design, not the current latest design. If the reason is that your page layout (with that account) does not have the old youtube design data, then yes, it will show nothing.

Need to rewrite that part to adopt the new design.

### Remarks

I am not sure you are familiar with front end programming or not.
You can check in your page that, there should be `<ytd-expander>` with classes "style-scope" and "ytd-video-secondary-info-renderer". This is the element detected by Tabview Youtube.

**Comment by cyfung1031** [comment]
Seem I have found a way to get this bug. Hope I can fix it soon.

**Comment by cyfung1031** [comment]
@ni1chigo2115 Fixed now. Please update and let me know it works or not.

**Comment by ni1chigo2115** [comment]
NO, I updated, but the newly created channel is better, but Summy doesn't seem to move on my main account that I usually use, I'll look for the condition again.

**Comment by cyfung1031** [comment]
@ni1chigo2115  Sorry I am a bit confused with your last comment. Can you please clarify?

So the latest version of Tabview Youtube can work perfectly with your brand account?
It works with and without YouTube EXPERIMENT_FLAGS Tamer Basic?

BTW, the bug in the previous version is my mistake. It was suddenly not working that if users enter the video page from the home page. That's not your problem :)

Should we close this issue now? Thanks.

**Comment by ni1chigo2115** [comment]
概要欄に関してはYouTube EXPERIMENT_FLAGS Tamer Basicなしではまだ正常に移動できないようです。
（おそらくEXPERIMENT_FLAGS Tamer Basicの対象になっている何かのフラグが長く使われたブランドアカウントに設定されているようです）
それ以外は正常に動作しています

**Comment by cyfung1031** [comment]
分かりました。確実に新たなEXPERIMENT_FLAGのことです。

特定のFLAGをまだ見つからないから、しばらくEXPERIMENT_FLAGS Tamer Basicを使っておいてください。

**Comment by cyfung1031** [comment]
> 概要欄に関しては YouTube EXPERIMENT_FLAGS Tamer Basic なしではまだ正常に移動できないようです。 （おそらく EXPERIMENT_FLAGS Tamer Basic の対象になっている何かのフラグが長く使われたブランドアカウントに設定されているようです） それ以外は正常に動作しています

`kevlar_watch_metadata_refresh_no_old_secondary_data` というFLAG を見つけたんです。直しました。
YouTube EXPERIMENT_FLAGS Tamer の最新バージョンをインストールしてみてください。

**Comment by ni1chigo2115** [comment]
修正を確認しました！
TVY、YEFT両方の修正対応してくれてありがとうございます！

**Comment by cyfung1031** [comment]
https://greasyfork.org/scripts/470428-youtube-experiment-flags-tamer/discussions/205941

そちらも「良い」にしてくださいね
